FROM grapevinehaus/elixir:1.9.4-1 as builder

RUN mix local.rebar --force && \
    mix local.hex --force

WORKDIR /app
ENV MIX_ENV=prod
COPY mix.* /app/
RUN mix deps.get --only prod

RUN mix deps.compile

FROM builder as releaser

COPY . /app/
RUN mix release && \
  cd _build/prod/rel/spigot/ && \
  tar czf /opt/spigot.tar.gz .
