name: Docker Builds
on:
  push:
    branches:
      - master
jobs:
  spigot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
        docker build -t grapevinehaus/spigot:${GITHUB_SHA} .
        docker push grapevinehaus/spigot:${GITHUB_SHA}
